In [4]:
import numpy as np
import math as m
import scipy as sc


In [5]:
array = (0.5 * (10 - np.arange(10, dtype=np.float64)))

In [6]:
array

array([5. , 4.5, 4. , 3.5, 3. , 2.5, 2. , 1.5, 1. , 0.5])

In [4]:
np.sum(sc.special.digamma(array))

4.79875249776617

In [5]:
phi = np.matrix(np.random.uniform(size=(50,100)))
phi = np.divide(phi, np.sum(phi, axis = 0))

In [6]:
phi

matrix([[0.03380841, 0.01985705, 0.02667818, ..., 0.03329468, 0.03882084,
         0.031086  ],
        [0.03417638, 0.0217681 , 0.01183568, ..., 0.00480964, 0.00548508,
         0.01328251],
        [0.02884706, 0.03448621, 0.012288  , ..., 0.01015911, 0.02891352,
         0.02069041],
        ...,
        [0.0322619 , 0.00893905, 0.01431854, ..., 0.02490075, 0.03562628,
         0.0395865 ],
        [0.03304226, 0.00728677, 0.02021011, ..., 0.03190196, 0.00282319,
         0.00493919],
        [0.01632996, 0.03340011, 0.03066431, ..., 0.0176675 , 0.004087  ,
         0.01806497]])

In [7]:
phi[:0:-1,:]

matrix([[0.01632996, 0.03340011, 0.03066431, ..., 0.0176675 , 0.004087  ,
         0.01806497],
        [0.03304226, 0.00728677, 0.02021011, ..., 0.03190196, 0.00282319,
         0.00493919],
        [0.0322619 , 0.00893905, 0.01431854, ..., 0.02490075, 0.03562628,
         0.0395865 ],
        ...,
        [0.03275372, 0.04045235, 0.02297701, ..., 0.02454229, 0.02713834,
         0.00102112],
        [0.02884706, 0.03448621, 0.012288  , ..., 0.01015911, 0.02891352,
         0.02069041],
        [0.03417638, 0.0217681 , 0.01183568, ..., 0.00480964, 0.00548508,
         0.01328251]])

In [8]:
array

array([5. , 4.5, 4. , 3.5, 3. , 2.5, 2. , 1.5, 1. , 0.5])

In [9]:
from scipy.special import digamma as phi

In [10]:
phi(array, axis=1)

TypeError: psi() got an unexpected keyword argument 'axis'

In [11]:
np.sum(array)

27.5

In [13]:
repeat_sum = np.repeat(np.sum(array), len(array))

In [15]:
repeat_sum - np.cumsum(array)

array([22.5, 18. , 14. , 10.5,  7.5,  5. ,  3. ,  1.5,  0.5,  0. ])

In [19]:
n = 100
k = 5
res = np.random.random_sample((n,k))
res

array([[0.84439705, 0.38778243, 0.42689679, 0.35740161, 0.67980562],
       [0.76659096, 0.10011691, 0.79020835, 0.89251612, 0.00710118],
       [0.83669766, 0.773433  , 0.95235018, 0.75230648, 0.09181021],
       [0.15195502, 0.09481039, 0.47489339, 0.50416878, 0.03561488],
       [0.25409397, 0.6586972 , 0.47039741, 0.21896894, 0.19576507],
       [0.80080737, 0.58798079, 0.23593032, 0.09387201, 0.34933186],
       [0.26966292, 0.44648145, 0.37169918, 0.32846439, 0.84559686],
       [0.85385464, 0.45186639, 0.88229042, 0.44694426, 0.74786551],
       [0.13056233, 0.19079372, 0.66144406, 0.89357733, 0.20599031],
       [0.37416886, 0.43442381, 0.06467301, 0.60350625, 0.77132793],
       [0.07479667, 0.92561547, 0.50590249, 0.49408603, 0.425596  ],
       [0.13870208, 0.13093168, 0.7925777 , 0.40490857, 0.57417594],
       [0.62083328, 0.73336459, 0.76774331, 0.97420708, 0.0920523 ],
       [0.72108354, 0.5813294 , 0.06733748, 0.74393585, 0.98582829],
       [0.27298665, 0.52656181, 0.

In [20]:
gamma = np.zeros((k, 2))

In [46]:
cumulative = np.cumsum(np.sum(res, 0))
aggregate = np.sum(res, 0)

In [48]:
gamma[:-1, 0] = aggregate[:-1] + 1

In [52]:
gamma[:-1, 1] = np.sum(cumulative[-1:] - cumulative, initial = 1.2)

In [60]:
(cumulative[-1:] - cumulative) + 1.2

array([200.67255886, 148.41869245,  97.45802224,  49.6460396 ,
         1.2       ])

In [59]:
gamma[:, 1]

array([492.59531314, 492.59531314, 492.59531314, 492.59531314,
         0.        ])

In [34]:
res[0,:]

array([0.84439705, 0.38778243, 0.42689679, 0.35740161, 0.67980562])

In [38]:
np.sum(np.array(res), 0)

array([47.08251968, 52.2538664 , 50.96067021, 47.81198264, 48.4460396 ])

In [40]:
np.cumsum(np.sum(res, 0))

array([ 47.08251968,  99.33638609, 150.2970563 , 198.10903894,
       246.55507854])

In [61]:
np.finfo(float).eps

2.220446049250313e-16

## Verosimilitud de los datos

In [2]:
def concentration(self, cluster, p, __nu, __cov_inverse):
    """
    This measure is used to determine how "concentrated" a Gaussian component (cluster) is around its mean.
    It is calculated as the sum of the squared Mahalanobis distances between each data point and the mean of the 
    cluster, weighted by the probability of each data point belonging to that cluster.
    """
    sum_phi = np.sum(phi((__nu[cluster] + 1 - np.arange(1, p + 1)) / 2))
    determinant = np.linalg.det(__cov_inverse[cluster])

    return sum_phi + p * m.log(2) + m.log(determinant)

def verosimilitude(cluster, instance, dataset, __responsabilities):
    x = dataset[instance]
    p = dataset.shape[1]
    distance = np.dot(__responsabilities, __responsabilities.T)

    if distance[cluster] < 1e-20:
        return 0

    concentration = concentration(cluster)
    x_bar_k = np.sum(np.multiply(x, __responsabilities[:, cluster]), 0) / distance[cluster]
    diff = x - x_bar_k

    S_k = np.dot(diff.T, np.multiply(diff, __responsabilities[:, cluster])) / distance[cluster]
    return 0.5 * distance[cluster] * (concentration - expected_distance(x, cluster))

In [3]:

        if (is_keep_l == 1) & (iter <= max_iter):
            term71 = 0
            term72 = 0
            term73 = 0
            term74 = 0
            term76 = 0
            term77 = 0

            for k in range(K):
                if N[k] > 10**(-10):
                    E_ln_lambda_k = np.sum(
                        sps.digamma((nuQ[k] + 1 - np.array(range(1, p + 1), dtype=np.float)) / 2)) 
                    + m.log(np.linalg.det(WQ[k, :, :]))
                    x_bar_k = np.sum(np.multiply(X, rQ[:, k]), 0) / N[k]
                    S_k = np.dot((X - x_bar_k).T, np.multiply(X - x_bar_k, rQ[:, k])) / N[k]
                    term71 = 
                        term71 + 
                        0.5 * N[k] * 
                    (E_ln_lambda_k - 
                     p / betaQ[k] - 
                     nuQ[k] * np.sum(np.diag(np.dot(S_k, WQ[k, :, :]) ) ) - 
                     nuQ[k] * np.dot(np.dot((x_bar_k - muQ[k, :, :].T), WQ[k, :, :]), ((x_bar_k - muQ[k, :, :].T)).T)
                    )

                if k < K - 1:
                    tmp = N[k] * (sps.digamma(gammaQ[k, 0]) - sps.digamma(np.sum(gammaQ[k, :])))
                    for j in range(k+1, K):
                        tmp = tmp + N[j] * (sps.digamma(gammaQ[k, 1]) - sps.digamma(np.sum(gammaQ[k, :])))

                    term72 = term72 + tmp
                    term73 = term73 + (alpha0 - 1) * (sps.digamma(gammaQ[k, 1]) - sps.digamma(np.sum(gammaQ[k, :])))

                tmp2 = (-p * beta0 / betaQ[k] - beta0 * nuQ[k] * np.dot(np.dot((muQ[k, :, :].T - mu0), WQ[k, :, :]), (((muQ[k, :,:].T - mu0).T) ))) / 2
                tmp3 = nuQ[k] * sum(np.diag(np.dot(np.linalg.inv(W0), WQ[k, :, :]))) / 2
                term74 = term74 + E_ln_lambda_k * (nu0 - p) / 2 + tmp2 - tmp3

                if k < K - 1:
                    term76 = term76 + (gammaQ[k, 0] - 1) * (sps.digamma(gammaQ[k, 0]) - sps.digamma(np.sum(gammaQ[k, :]))) + (gammaQ[k, 1] - 1) * (sps.digamma(gammaQ[k, 1]) - sps.digamma(np.sum(gammaQ[k, :]))) - sps.betaln(gammaQ[k, 0], gammaQ[k, 1])

                term77 = term77 + E_ln_lambda_k / 2 + p / 2 * m.log(betaQ[k]) - H(WQ[k, :, :], nuQ[k])

            ElnP = sps.digamma(alpha_p) - sps.digamma(alpha_p + beta_p)
            ElnMinusP = sps.digamma(beta_p) - sps.digamma(alpha_p + beta_p)
            ElnQ = sps.digamma(alpha_q) - sps.digamma(alpha_q + beta_q)
            ElnMinusQ = sps.digamma(beta_q) - sps.digamma(alpha_q + beta_q)
            tmpRQ = np.dot(rQ, rQ.T)
            termE_lnPez = np.sum(np.multiply(np.multiply(constraints, checked), tmpRQ)) * ElnP + np.sum(np.multiply(np.multiply(1 - constraints, checked), tmpRQ)) * ElnMinusP + np.sum(np.multiply(np.multiply(constraints, checked), 1 - tmpRQ)) * ElnMinusQ + np.sum(np.multiply(np.multiply(1 - constraints, checked), 1 - tmpRQ)) * ElnQ
            termE_ln_pq = (alpha_p_0 - alpha_p) * ElnP + (beta_p_0 - beta_p) * ElnMinusP + (alpha_q_0 - alpha_q) * ElnQ + (beta_q_0 - beta_q) * ElnMinusQ + sps.betaln(alpha_p, beta_p) + sps.betaln(alpha_q, beta_q)

            L[iter] = term71 + term72 + term73 + term74 - term75 - term76 - term77 + termE_lnPez + termE_ln_pq

            pImprove = 1
            if iter > 0:
                pImprove = (L[iter] - L[iter - 1]) / np.absolute(L[iter - 1])

        if pImprove < stop_thr:
            nRun = iter
            iter = max_iter + 1

        iter += 1

    membership_vector = np.array([np.argmax(rQ[i, :]) for i in range(np.shape(rQ)[0])], dtype=np.uint8)

    return membership_vector

In [7]:
np.dot(array.T, array)

96.25

In [8]:
array

array([5. , 4.5, 4. , 3.5, 3. , 2.5, 2. , 1.5, 1. , 0.5])

In [10]:
np.sum(array * array)

96.25